### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by bnbaek** [composite/jQuery.paging#2]
안녕하세요. 개발자님
항상 잘 사용하고 있습니다.
감사합니다.
onclick 이벤트를 사용하고 있습니다.
링크 주소(#3)을 안보이게 할수는 있는지 궁금합니다.

**Comment by composite** [comment]
a 외 태그를 쓰면 가능하며 a 태그일 경우 소스 수정 없이 불가능합니다. 물론 개선 계획 없습니다.
