### ISSUE TITLE
기능문의 드립니다.

### ISSUE THREAD

**Issue by redldm** [composite/jQuery.paging#3]
안녕하세요 공개 해주신 소스 보고 적용하여 잘 사용 하고 있습니다.
그런데 디자인적이 이슈가 생겨. 아래와 같은 기능 문의 드립니다.
처음,이전,다음,마지막 이런버튼들이 사라지지 않고 링크만 비활성된채 계속 보이게 하고 싶습니다.
이런 기능이 있는지 있으면 어떻게 수정하면 되는지 답변 부탁드립니다.

항상 감사드립니다.

**Comment by composite** [comment]
내부 함수 `make()` 호출 부분에서 if 조건 부분을 class 넣는 곳에 적용하여 원하는 class 명 넣어서 수정하시면 됩니다.
